### ISSUE TITLE
Add German translations

### ISSUE THREAD

**Issue by rohanagarwal94** [rohanagarwal94/easy_hacktoberfest_task#2]
Create a separate xml file just like given in the repo using the same keys and add corresponding translations for the english values.

**Comment by mafenet** [comment]
I would like to take this one. I assume that the fields forapp name, facebook app name and magic assistant do not need to be translated?

**Comment by rohanagarwal94** [comment]
yeah, leave out the strings which have tag - translable - false. Please go ahead.
