### ISSUE TITLE
Add Dutch translations

### ISSUE THREAD

**Issue by rohanagarwal94** [rohanagarwal94/easy_hacktoberfest_task#24]
Create a separate xml file just like given in the repo using the same keys and add corresponding translations for the english values.

**Comment by StefanJanssen95** [comment]
Although most dutch people prefer English in software I added the translations in pull request #29

**Comment by rohanagarwal94** [comment]
didnt know that. Anyway on android, these translations take place depending on users default language of the phone. So thats not an issue.
