### ISSUE TITLE
Add spanish translations

### ISSUE THREAD

**Issue by rohanagarwal94** [rohanagarwal94/easy_hacktoberfest_task#3]
Create a separate xml file just like given in the repo using the same keys and add corresponding translations for the english values.

**Comment by peter-parque** [comment]
Can I take this?

**Comment by rohanagarwal94** [comment]
yeah sure, go ahead.

**Comment by RacZo** [comment]
Do you still need help?

**Comment by citec** [comment]
Issue is reopened, do you need more help? I am native spaniard

**Comment by rohanagarwal94** [comment]
hey @citec , i just merged @peter-parque PR. If you feel he wrongly translated something, feel free to send another PR. If there are major changes, I will merge them. Closing this for now.
